#!/bin/bash
# AES 2.0 V8 — One-time setup script
# Run once after cloning: bash setup.sh
set -euo pipefail

echo "============================================"
echo " AES 2.0 V8 — Environment Setup"
echo "============================================"
echo ""

# ── 1. Detect project root ──
PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
echo "[1] Project root: $PROJECT_ROOT"

# ── 2. Find or set model path ──
echo ""
echo "[2] Base model configuration"
echo "    Looking for Gemma 4 E4B model..."

MODEL_PATH="${MODEL_PATH:-}"
if [ -z "$MODEL_PATH" ]; then
    # Try common locations
    for candidate in \
        "$PROJECT_ROOT/../gemma-4-E4B-it-local" \
        "$HOME/gemma-4-E4B-it-local" \
        "/home/public/new_dl/gemma-4-E4B-it-local"; do
        if [ -d "$candidate" ] && [ -f "$candidate/config.json" ]; then
            MODEL_PATH="$candidate"
            break
        fi
    done
fi

if [ -z "$MODEL_PATH" ]; then
    echo "    WARNING: Model not found."
    echo "    Download from: https://huggingface.co/google/gemma-4-4b-it"
    echo "    Then run: export MODEL_PATH=/path/to/model"
    echo "    Or edit config/base_config_ordinal_v8.yaml directly"
else
    echo "    Found: $MODEL_PATH"
fi

# ── 3. Create directory structure ──
echo ""
echo "[3] Creating directory structure..."
mkdir -p "$PROJECT_ROOT/data/processed"
mkdir -p "$PROJECT_ROOT/outputs/oof"
mkdir -p "$PROJECT_ROOT/outputs/v8_kfold"
mkdir -p "$PROJECT_ROOT/logs"
mkdir -p "$PROJECT_ROOT/results"
echo "    Done"

# ── 4. Check Python environment ──
echo ""
echo "[4] Checking Python environment..."
if command -v python3 &>/dev/null; then
    PYTHON=$(command -v python3)
elif command -v python &>/dev/null; then
    PYTHON=$(command -v python)
else
    echo "    ERROR: Python not found. Install Python 3.10+"
    exit 1
fi
echo "    Python: $PYTHON ($($PYTHON --version))"

# ── 5. Check dependencies ──
echo ""
echo "[5] Checking key dependencies..."
$PYTHON -c "import torch; print(f'    PyTorch {torch.__version__}')" 2>/dev/null || \
    echo "    WARNING: PyTorch not found. Run: pip install -r requirements.txt"
$PYTHON -c "import transformers; print(f'    Transformers {transformers.__version__}')" 2>/dev/null || \
    echo "    WARNING: Transformers not found. Run: pip install -r requirements.txt"
$PYTHON -c "import peft; print(f'    PEFT {peft.__version__}')" 2>/dev/null || \
    echo "    WARNING: PEFT not found. Run: pip install -r requirements.txt"

# ── 6. Generate config override ──
if [ -n "$MODEL_PATH" ]; then
    echo ""
    echo "[6] Writing local config override..."
    cat > "$PROJECT_ROOT/config/config_local.yaml" << EOF
# Auto-generated by setup.sh — overrides base config
# Do NOT commit this file to git
model:
  model_id: '$MODEL_PATH'
EOF
    echo "    config/config_local.yaml created"
fi

# ── 7. Status summary ──
echo ""
echo "============================================"
echo " Setup Complete"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Prepare data: place train_old.csv + train_new.csv in data/"
echo "  2. Run: bash scripts/prepare_data.sh (to be created)"
echo "  3. Train: bash run_v8_kfold.sh"
echo ""
echo "Quick test (CPU only):"
echo "  python -c 'from stage2_train.prompt import format_prompt; print(format_prompt(\"Test.\")[:100])'"
echo ""
echo "Optional — install deps:"
echo "  pip install -r requirements.txt"
